# This action should only be run on pull_request events
name: "Login"
description: "Login to Bytebase and obtain an API token"
inputs:
  url:
    description: "The Bytebase URL. Example: https://bytebase.example.com"
    required: true
  headers:
    description: 'JSON string of extra headers to include in the request. e.g Cloudflare Zero Trust headers {"CF-Access-Client-Id": "xxx", CF-Access-Client-Secret: "xxx"}'
  service-account:
    description: "The service account to use for authentication"
    required: true
  service-account-key:
    description: "The service account key to use for authentication"
    required: true
outputs:
  token:
    description: "The API token obtained from bytebase/login action"
runs:
  using: "node20"
  main: "dist/index.js"
