# This action should only be run on pull_request events
name: "Upsert Issue"
description: "Upsert the issue"
inputs:
  github-token:
    description: "GitHub token for accessing the API"
    required: true
  pattern:
    description: "Glob pattern to match changed files"
    required: true
    default: "**/*.up.sql"
  url:
    description: "The Bytebase URL. Example: https://bytebase.example.com"
    required: true
  token:
    description: "The API token obtained from bytebase/login action"
    required: true
  headers:
    description: 'JSON string of extra headers to include in the request. e.g Cloudflare Zero Trust headers {"CF-Access-Client-Id": "xxx", CF-Access-Client-Secret: "xxx"}'
  project-id:
    description: "The project ID. Example: example"
    required: true
  database:
    description: "The name of database. Example: instances/prod-instance/databases/example"
    required: true
  title:
    description: "The title of the issue"
    required: true
  description:
    description: "The description of the issue"
    required: true
    default: ""
  assignee:
    description: "The assignee of the issue"
runs:
  using: "node20"
  main: "dist/index.js"
